# Generated by Django 6.0.7 on 2026-09-17 16:11

import saxo.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnableBankingCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(choices=[('kbc', 'KBC'), ('argenta', 'Argenta')], max_length=20, unique=True)),
                ('session_id', saxo.fields.EncryptedTextField()),
                ('valid_until', models.DateTimeField()),
                ('linked_accounts', models.JSONField(default=list)),
                ('needs_reauth', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BankSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(choices=[('kbc', 'KBC'), ('argenta', 'Argenta')], max_length=20)),
                ('outcome', models.CharField(choices=[('ok', 'Completed'), ('skipped', 'Skipped'), ('failed', 'Failed')], max_length=10)),
                ('detail', models.CharField(blank=True, default='', max_length=200)),
                ('rows', models.PositiveIntegerField(default=0)),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ran_at', '-id'],
                'indexes': [models.Index(fields=['bank', '-ran_at'], name='bsr_bank_ran_at_idx')],
            },
        ),
    ]
