# Generated by Django 6.0.7 on 2026-09-18 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_bankaccount_currency'),
        ('enablebanking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(choices=[('kbc', 'KBC'), ('argenta', 'Argenta')], max_length=20)),
                ('external_id', models.CharField(max_length=128, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('booking_date', models.DateField()),
                ('counterparty_name', models.CharField(blank=True, default='', max_length=200)),
                ('counterparty_iban', models.CharField(blank=True, default=None, max_length=34, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('category', models.CharField(choices=[('GROCERIES', 'Groceries'), ('DINING', 'Dining'), ('TRANSPORT', 'Transport'), ('UTILITIES', 'Utilities'), ('SUBSCRIPTIONS', 'Subscriptions'), ('SHOPPING', 'Shopping'), ('HEALTH', 'Health'), ('TRAVEL', 'Travel'), ('ENTERTAINMENT', 'Entertainment'), ('INCOME', 'Income'), ('TRANSFER', 'Transfer'), ('SAVINGS', 'Savings'), ('REFUND_CREDIT', 'Refund/Credit'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('category_override', models.CharField(blank=True, choices=[('GROCERIES', 'Groceries'), ('DINING', 'Dining'), ('TRANSPORT', 'Transport'), ('UTILITIES', 'Utilities'), ('SUBSCRIPTIONS', 'Subscriptions'), ('SHOPPING', 'Shopping'), ('HEALTH', 'Health'), ('TRAVEL', 'Travel'), ('ENTERTAINMENT', 'Entertainment'), ('INCOME', 'Income'), ('TRANSFER', 'Transfer'), ('SAVINGS', 'Savings'), ('REFUND_CREDIT', 'Refund/Credit'), ('OTHER', 'Other')], default=None, max_length=20, null=True)),
            ],
            options={
                'ordering': ['-booking_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ManualIbanLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=34, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('GROCERIES', 'Groceries'), ('DINING', 'Dining'), ('TRANSPORT', 'Transport'), ('UTILITIES', 'Utilities'), ('SUBSCRIPTIONS', 'Subscriptions'), ('SHOPPING', 'Shopping'), ('HEALTH', 'Health'), ('TRAVEL', 'Travel'), ('ENTERTAINMENT', 'Entertainment'), ('INCOME', 'Income'), ('TRANSFER', 'Transfer'), ('SAVINGS', 'Savings'), ('REFUND_CREDIT', 'Refund/Credit'), ('OTHER', 'Other')], default='SAVINGS', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_key', models.CharField(max_length=200, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('GROCERIES', 'Groceries'), ('DINING', 'Dining'), ('TRANSPORT', 'Transport'), ('UTILITIES', 'Utilities'), ('SUBSCRIPTIONS', 'Subscriptions'), ('SHOPPING', 'Shopping'), ('HEALTH', 'Health'), ('TRAVEL', 'Travel'), ('ENTERTAINMENT', 'Entertainment'), ('INCOME', 'Income'), ('TRANSFER', 'Transfer'), ('SAVINGS', 'Savings'), ('REFUND_CREDIT', 'Refund/Credit'), ('OTHER', 'Other')], default='SUBSCRIPTIONS', max_length=20)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cadence', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('last_charged', models.DateField()),
                ('dismissed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-last_charged'],
            },
        ),
        migrations.RemoveIndex(
            model_name='banksyncrun',
            name='bsr_bank_ran_at_idx',
        ),
        migrations.AddField(
            model_name='banksyncrun',
            name='kind',
            field=models.CharField(choices=[('balances', 'Balances'), ('transactions', 'Transactions')], default='balances', max_length=20),
        ),
        migrations.AddIndex(
            model_name='banksyncrun',
            index=models.Index(fields=['bank', 'kind', '-ran_at'], name='bsr_bank_kind_ran_idx'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to='accounts.bankaccount'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['-booking_date', '-id'], name='bktx_date_id_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['bank_account', '-booking_date'], name='bktx_account_date_idx'),
        ),
    ]
