# Generated by Django 6.0.7 on 2026-09-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enablebanking', '0002_banktransaction_manualibanlabel_subscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('GROCERIES', 'Groceries'), ('DINING', 'Dining'), ('TRANSPORT', 'Transport'), ('UTILITIES', 'Utilities'), ('SUBSCRIPTIONS', 'Subscriptions'), ('SHOPPING', 'Shopping'), ('HEALTH', 'Health'), ('TRAVEL', 'Travel'), ('ENTERTAINMENT', 'Entertainment'), ('OTHER', 'Other')], max_length=20, unique=True)),
                ('monthly_limit', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
