# Generated by Django 6.0.7 on 2026-09-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enablebanking', '0003_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualibanlabel',
            name='counterparty_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='manualibanlabel',
            name='iban',
            field=models.CharField(blank=True, default=None, max_length=34, null=True, unique=True),
        ),
    ]
