# Generated by Django 6.0.7 on 2026-07-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('iban_masked', models.CharField(max_length=34)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('available', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gradient', models.CharField(blank=True, default=True, max_length=100)),
                ('accent', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
    ]
