# Generated by Django 6.0.7 on 2026-07-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='gradient',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
