# Generated by Django 6.0.7 on 2026-09-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_bankaccount_gradient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['bank', 'type']},
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='external_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True),
        ),
    ]
