# Generated by Django 6.0.7 on 2026-09-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_backfill_saxo_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
    ]
