# Generated by Django 6.0.7 on 2026-10-05 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('firm', models.CharField(max_length=160)),
                ('cik', models.PositiveIntegerField(unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('blurb', models.TextField(blank=True, default='')),
                ('curated', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_filing_at', models.DateField(blank=True, null=True)),
                ('quarters_expected', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('cusip', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('ticker', models.CharField(blank=True, max_length=16, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('figi', models.CharField(blank=True, default='', max_length=12)),
                ('security_type', models.CharField(blank=True, default='', max_length=60)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_end', models.DateField()),
                ('filed_on', models.DateField()),
                ('accession', models.CharField(max_length=20, unique=True)),
                ('form', models.CharField(choices=[('13F-HR', '13F-HR'), ('13F-HR/A', '13F-HR/A')], max_length=10)),
                ('amendment_type', models.CharField(blank=True, choices=[('', 'Original'), ('RESTATEMENT', 'Restatement'), ('NEW HOLDINGS', 'New holdings')], default='', max_length=12)),
                ('total_value', models.BigIntegerField()),
                ('positions', models.PositiveIntegerField()),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filings', to='investors.investor')),
            ],
            options={
                'ordering': ['-quarter_end', 'filed_on', 'accession'],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusip', models.CharField(max_length=9)),
                ('issuer', models.CharField(max_length=200)),
                ('title_of_class', models.CharField(blank=True, default='', max_length=150)),
                ('shares', models.BigIntegerField()),
                ('amount_type', models.CharField(choices=[('SH', 'Shares'), ('PRN', 'Principal')], default='SH', max_length=3)),
                ('value', models.BigIntegerField()),
                ('put_call', models.CharField(blank=True, choices=[('', 'None'), ('PUT', 'Put'), ('CALL', 'Call')], default='', max_length=4)),
                ('discretion', models.CharField(blank=True, default='', max_length=10)),
                ('filing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='investors.filing')),
            ],
            options={
                'indexes': [models.Index(fields=['cusip'], name='holding_cusip_idx')],
                'constraints': [models.UniqueConstraint(fields=('filing', 'cusip', 'put_call'), name='holding_filing_cusip_side')],
            },
        ),
        migrations.AddIndex(
            model_name='filing',
            index=models.Index(fields=['investor', '-quarter_end'], name='filing_investor_quarter_idx'),
        ),
        migrations.AddConstraint(
            model_name='filing',
            constraint=models.UniqueConstraint(fields=('investor', 'quarter_end', 'accession'), name='filing_investor_quarter_accession'),
        ),
    ]
