# Generated by Django 6.0.7 on 2026-10-07 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='followed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investor',
            name='styles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='PositionMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_end', models.DateField()),
                ('cusip', models.CharField(max_length=9)),
                ('put_call', models.CharField(blank=True, default='', max_length=4)),
                ('issuer', models.CharField(max_length=200)),
                ('kind', models.CharField(blank=True, max_length=10, null=True)),
                ('shares', models.BigIntegerField()),
                ('previous_shares', models.BigIntegerField(blank=True, null=True)),
                ('value', models.BigIntegerField()),
                ('previous_value', models.BigIntegerField(blank=True, null=True)),
                ('weight_pct', models.FloatField()),
                ('previous_weight_pct', models.FloatField(blank=True, null=True)),
                ('change_pct', models.FloatField(blank=True, null=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='investors.investor')),
            ],
            options={
                'indexes': [models.Index(fields=['quarter_end', 'kind'], name='move_quarter_kind_idx'), models.Index(fields=['cusip'], name='move_cusip_idx')],
                'constraints': [models.UniqueConstraint(fields=('investor', 'quarter_end', 'cusip', 'put_call'), name='move_investor_quarter_holding')],
            },
        ),
    ]
