# Generated by Django 6.0.7 on 2026-07-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Positionp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('avg_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sector', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('STOCK', 'Stock'), ('ETF', 'ETF')], max_length=10)),
                ('color', models.CharField(max_length=7)),
            ],
            options={
                'ordering': ['-ticker'],
            },
        ),
    ]
