# Generated by Django 6.0.7 on 2026-07-14 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Positionp',
            new_name='Position',
        ),
    ]
