# Generated by Django 6.0.7 on 2026-09-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_positionp_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='asset_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='uic',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
