# Generated by Django 6.0.7 on 2026-09-03 21:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_position_asset_type_position_uic'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='saxo', max_length=32, unique=True)),
                ('currency', models.CharField(max_length=3)),
                ('cash_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('positions_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('as_of', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='currency',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='position',
            name='fx_rate',
            field=models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=18),
        ),
        migrations.AddField(
            model_name='position',
            name='price_source',
            field=models.CharField(choices=[('live', 'Live price'), ('derived', 'Derived from Saxo P/L'), ('cost', 'Open price (unpriced)')], default='live', max_length=10),
        ),
        migrations.AddField(
            model_name='position',
            name='priced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='qty',
            field=models.DecimalField(decimal_places=4, max_digits=16),
        ),
    ]
