# Generated by Django 6.0.7 on 2026-09-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfoliovaluation_position_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='isin',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
    ]
