# Generated by Django 6.0.7 on 2026-09-13 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_position_isin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='isin',
        ),
    ]
