from django.urls import path, re_path

from .views import (
    ChartView,
    CompanyNewsView,
    DiscoverShelfView,
    DiscoverView,
    StartDiscoverScanView,
    EarningsCalendarView,
    FundamentalsView,
    InstrumentDetailsView,
    InstrumentSearchView,
    PeersView,
    PriceLineDetailView,
    PriceLineListCreateView,
    QuotesView,
    SymbolEarningsView,
    SymbolNoteReviewView,
    SymbolNoteView,
    TextAnnotationDetailView,
    TextAnnotationListCreateView,
    TrendLineDetailView,
    TrendLineListCreateView,
    WatchlistDetailView,
    WatchlistItemCreateView,
    WatchlistItemDeleteView,
    WatchlistListCreateView,
)

urlpatterns = [
    path('discover/', DiscoverView.as_view(), name='research-discover'),
    path('discover/scan/', StartDiscoverScanView.as_view(), name='research-discover-scan'),
    path('discover/<slug:key>/', DiscoverShelfView.as_view(), name='research-discover-shelf'),
    path('chart/', ChartView.as_view(), name='research-chart'),
    path('quotes/', QuotesView.as_view(), name='research-quotes'),
    path('fundamentals/<str:symbol>/', FundamentalsView.as_view(), name='research-fundamentals'),
    path('peers/<str:symbol>/', PeersView.as_view(), name='research-peers'),
    path(
        'earnings/calendar/',
        EarningsCalendarView.as_view(),
        name='research-earnings-calendar',
    ),
    path(
        'earnings/<str:symbol>/',
        SymbolEarningsView.as_view(),
        name='research-earnings-symbol',
    ),
    path('news/<str:symbol>/', CompanyNewsView.as_view(), name='research-company-news'),
    path('notes/<str:symbol>/', SymbolNoteView.as_view(), name='research-symbol-note'),
    path('notes/<str:symbol>/review/', SymbolNoteReviewView.as_view(), name='research-symbol-note-review'),
    re_path(
        r'^price-lines/(?P<uic>[0-9]+)/(?P<asset_type>[A-Za-z]{1,20})/$',
        PriceLineListCreateView.as_view(),
        name='research-price-lines',
    ),
    path('price-lines/<int:pk>/', PriceLineDetailView.as_view(), name='research-price-line'),
    re_path(
        r'^trend-lines/(?P<uic>[0-9]+)/(?P<asset_type>[A-Za-z]{1,20})/$',
        TrendLineListCreateView.as_view(),
        name='research-trend-lines',
    ),
    path('trend-lines/<int:pk>/', TrendLineDetailView.as_view(), name='research-trend-line'),
    re_path(
        r'^text-annotations/(?P<uic>[0-9]+)/(?P<asset_type>[A-Za-z]{1,20})/$',
        TextAnnotationListCreateView.as_view(),
        name='research-text-annotations',
    ),
    path('text-annotations/<int:pk>/', TextAnnotationDetailView.as_view(), name='research-text-annotation'),
    path('instruments/', InstrumentSearchView.as_view(), name='research-instruments'),
    path(
        'instruments/<int:uic>/<str:asset_type>/',
        InstrumentDetailsView.as_view(),
        name='research-instrument-details',
    ),
    path('watchlists/', WatchlistListCreateView.as_view(), name='watchlist-list'),
    path('watchlists/<int:pk>/', WatchlistDetailView.as_view(), name='watchlist-detail'),
    path(
        'watchlists/<int:pk>/items/',
        WatchlistItemCreateView.as_view(),
        name='watchlist-item-create',
    ),
    path(
        'watchlists/<int:pk>/items/<int:item_pk>/',
        WatchlistItemDeleteView.as_view(),
        name='watchlist-item-delete',
    ),
]
