# Generated by Django 6.0.7 on 2026-09-02 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('uic', models.PositiveIntegerField(blank=True, null=True)),
                ('asset_type', models.CharField(default='Stock', max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=120)),
                ('exchange', models.CharField(blank=True, default='', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='research.watchlist')),
            ],
            options={
                'ordering': ['added_at', 'id'],
                'unique_together': {('watchlist', 'symbol')},
            },
        ),
    ]
