# Generated by Django 6.0.7 on 2026-09-04 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlistitem',
            unique_together={('watchlist', 'uic')},
        ),
    ]
