# Generated by Django 6.0.7 on 2026-09-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_watchlistitem_uic_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('business_summary', models.TextField(blank=True, default='')),
                ('risks_to_watch', models.TextField(blank=True, default='')),
                ('bull_case', models.TextField(blank=True, default='')),
                ('bear_case', models.TextField(blank=True, default='')),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sell_trigger', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
    ]
