# Generated by Django 6.0.7 on 2026-09-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_symbolnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbolnote',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
