# Generated by Django 6.0.7 on 2026-09-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_symbolnote_reviewed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbolnote',
            name='stop_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
