# Generated by Django 6.0.7 on 2026-09-27 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_symbolnote_stop_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uic', models.PositiveIntegerField()),
                ('asset_type', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['uic', 'asset_type'], name='research_pr_uic_4040a0_idx')],
            },
        ),
    ]
