# Generated by Django 6.0.7 on 2026-09-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_priceline'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceline',
            name='label',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
