# Generated by Django 6.0.7 on 2026-09-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_priceline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenerRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('sector', models.CharField(blank=True, default='', max_length=60)),
                ('indexes', models.CharField(max_length=20)),
                ('uic', models.PositiveIntegerField(blank=True, null=True)),
                ('asset_type', models.CharField(default='Stock', max_length=20)),
                ('last_close', models.FloatField(blank=True, null=True)),
                ('change_1d', models.FloatField(blank=True, null=True)),
                ('change_1m', models.FloatField(blank=True, null=True)),
                ('change_3m', models.FloatField(blank=True, null=True)),
                ('change_1y', models.FloatField(blank=True, null=True)),
                ('ma50', models.FloatField(blank=True, null=True)),
                ('ma200', models.FloatField(blank=True, null=True)),
                ('pct_vs_ma200', models.FloatField(blank=True, null=True)),
                ('rsi14', models.FloatField(blank=True, null=True)),
                ('pct_from_52w_high', models.FloatField(blank=True, null=True)),
                ('rvol', models.FloatField(blank=True, null=True)),
                ('sparkline', models.JSONField(blank=True, default=list)),
                ('pe', models.FloatField(blank=True, null=True)),
                ('forward_pe', models.FloatField(blank=True, null=True)),
                ('roe', models.FloatField(blank=True, null=True)),
                ('net_margin', models.FloatField(blank=True, null=True)),
                ('eps_growth_5y', models.FloatField(blank=True, null=True)),
                ('debt_to_equity', models.FloatField(blank=True, null=True)),
                ('dividend_yield', models.FloatField(blank=True, null=True)),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('technicals_at', models.DateTimeField(blank=True, null=True)),
                ('fundamentals_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('unmatched', 'Unmatched'), ('failed', 'Failed')], default='unmatched', max_length=10)),
                ('error', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
    ]
