# Generated by Django 6.0.7 on 2026-09-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0008_priceline_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uic', models.PositiveIntegerField()),
                ('asset_type', models.CharField(max_length=20)),
                ('start_bar_date', models.DateField()),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('end_bar_date', models.DateField()),
                ('end_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('label', models.CharField(blank=True, default='', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['uic', 'asset_type'], name='research_tr_uic_0aae5f_idx')],
            },
        ),
    ]
