# Generated by Django 6.0.7 on 2026-10-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0009_trendline'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uic', models.PositiveIntegerField()),
                ('asset_type', models.CharField(max_length=20)),
                ('bar_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('text', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['uic', 'asset_type'], name='research_te_uic_065e7e_idx')],
            },
        ),
    ]
