# Generated by Django 6.0.7 on 2026-10-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0011_screenerrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenerrow',
            name='next_earnings_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screenerrow',
            name='payout_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screenerrow',
            name='revenue_growth_5y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
