# Generated by Django 6.0.7 on 2026-08-06 19:54

import saxo.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaxoCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', saxo.fields.EncryptedTextField()),
                ('refresh_token', saxo.fields.EncryptedTextField()),
                ('expires_at', models.DateTimeField()),
                ('environment', models.CharField(choices=[('sim', 'Simulation'), ('live', 'Live')], default='sim', max_length=10)),
                ('needs_reauth', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
