# Generated by Django 6.0.7 on 2026-09-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saxo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saxocredential',
            name='last_synced_at',
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=64)),
                ('outcome', models.CharField(choices=[('ok', 'Completed'), ('skipped', 'Skipped'), ('failed', 'Failed')], max_length=10)),
                ('detail', models.CharField(blank=True, default='', max_length=200)),
                ('rows', models.PositiveIntegerField(default=0)),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ran_at', '-id'],
                'indexes': [models.Index(fields=['-ran_at', '-id'], name='syncrun_ran_at_desc_idx')],
            },
        ),
    ]
