# Generated by Django 6.0.7 on 2026-09-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saxo', '0002_remove_saxocredential_last_synced_at_syncrun'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='syncrun',
            index=models.Index(fields=['task', '-ran_at'], name='syncrun_task_ran_idx'),
        ),
    ]
