# Generated by Django 6.0.7 on 2026-07-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DIVIDEND', 'Dividend'), ('DEPOSIT', 'Deposit'), ('FEE', 'Fee')], max_length=10)),
                ('instrument', models.CharField(max_length=100)),
                ('ticker', models.CharField(blank=True, default='-', max_length=10)),
                ('qty', models.DecimalField(decimal_places=4, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account', models.CharField(default='Saxo', max_length=50)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
