# Generated by Django 6.0.7 on 2026-08-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='saxo_trade_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True),
        ),
    ]
