# Generated by Django 6.0.7 on 2026-07-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetWorkSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('portfolio_valie', models.DecimalField(decimal_places=2, max_digits=14)),
                ('bank_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('net_worth', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
