# Generated by Django 6.0.7 on 2026-07-26 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NetWorkSnapshot',
            new_name='NetWorthSnapshot',
        ),
    ]
