# Generated by Django 6.0.7 on 2026-07-26 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_networksnapshot_networthsnapshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networthsnapshot',
            old_name='portfolio_valie',
            new_name='portfolio_value',
        ),
    ]
