# Generated by Django 6.0.7 on 2026-09-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_portfolio_valie_networthsnapshot_portfolio_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='networthsnapshot',
            name='saxo_account_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=14, null=True),
        ),
    ]
