# Generated by Django 6.0.7 on 2026-09-23 18:28

from django.db import migrations, models


def reclassify_existing_rows(apps, schema_editor):
    NetWorthSnapshot = apps.get_model('core', 'NetWorthSnapshot')
    # Rows with a saxo_account_value can be exactly recomputed as
    # bank_total + saxo_account_value (RECONCILED) - this is not a guess,
    # it uses figures already stored on the row. Rows without one keep
    # their existing net_worth (already portfolio_value + bank_total, i.e.
    # exactly what APPROXIMATE means) and the model default already marks
    # them APPROXIMATE, so nothing to do for those.
    for snap in NetWorthSnapshot.objects.exclude(saxo_account_value__isnull=True):
        snap.net_worth = snap.bank_total + snap.saxo_account_value
        snap.net_worth_basis = 'reconciled'
        snap.save(update_fields=['net_worth', 'net_worth_basis'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_networthsnapshot_saxo_account_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='networthsnapshot',
            name='net_worth_basis',
            field=models.CharField(choices=[('reconciled', 'Reconciled (bank + Saxo cash+positions)'), ('approximate', 'Approximate (bank + positions only - Saxo cash unavailable)')], default='approximate', max_length=12),
        ),
        migrations.RunPython(reclassify_existing_rows, noop),
    ]
